name: defaultIV

geometry:
  inner_radius: 0.366

materials:
  M1:
    stiffness:
      type: matrix
      scale: 1.0e+9
      C:
        - [159.9998, 3.3195, 3.8702, 0, 0, 0]
        - [3.3195, 10.4519, 2.5826, 0, 0, 0]
        - [3.8702, 2.5826, 10.4767, 0, 0, 0]
        - [0, 0, 0, 5.25, 0, 0]
        - [0, 0, 0, 0, 3.05, 0]
        - [0, 0, 0, 0, 0, 5.25]
    failure:
      Xt: 2180.0e+6
      Xc: 1200.0e+6
      Yt: 60.0e+6
      Yc: 140.0e+6
      S12: 136.0e+6
      S13: 136.0e+6
      S23: 86.9e+6

layup:
  - {angles_deg: [89.0],          repeat: 5,  thickness: 0.3128e-3, material: M8}
  - {angles_deg: [12.0, -12.0],   repeat: 2,  thickness: 0.3128e-3, material: M8}
  - {angles_deg: [89.0],          repeat: 19, thickness: 0.3128e-3, material: M8}
  - {angles_deg: [12.0, -12.0],   repeat: 5,  thickness: 0.3128e-3, material: M8}
  - {angles_deg: [89.0],          repeat: 19, thickness: 0.3128e-3, material: M8}
  - {angles_deg: [12.0, -12.0],   repeat: 5,  thickness: 0.3128e-3, material: M8}
  - {angles_deg: [89.0],          repeat: 6,  thickness: 0.3128e-3, material: M8}
  - {angles_deg: [12.0, -12.0],   repeat: 17, thickness: 0.3128e-3, material: M8}
